[package]
name = "tcpip_tester"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
pnet = "0.33"
eframe = "0.22"
anyhow = "1.0" 